apiVersion: v1
kind: Service
metadata:
  name:  httpd-frontend-service
spec:
  selector:
    app: httpd
    tier: frontend
  type: NodePort
  ports:
  - name:  portforweb
    port:  80
    targetPort:  80
    nodePort: 30008
